### ISSUE TITLE
FiggureS1.png issues

### ISSUE THREAD

**Issue by jaytlennon** [LennonLab/ReservoirGradient#2]
--> Units of TP micrograms /L as opposed to milligrams?
--> Chlorophyll a: 
          --"A" should be lower case and italicized
          -- should be micrograms and not milligrams
--> Dissolved oxygen near damn appears to be ~25 mg/L. That's pretty high. Do we trust that?
--> pH panel seems to be plotting dissolved oxygen

**Comment by meganllarsen** [comment]
I've addressed these issues (whith the exception of the italicis) with the latest pull.
